spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc5th?useSSL=false&serverTimezone=Asia/Seoul
    username: sumin
    password: 9030
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always